language: node_js
node_js:
  - 13

services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - echo "no tests"

script:
  - docker build -t $DOCKER_USERNAME/udagram-api-user:v1 ./udagram-api-user
  - docker build -t $DOCKER_USERNAME/udagram-api-feed:v1 ./udagram-api-feed
  - docker build -t $DOCKER_USERNAME/reverseproxy:v1 ./reverseproxy
  - docker build -t $DOCKER_USERNAME/udagram-frontend:v1 ./udagram-frontend
  - docker images

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push $DOCKER_USERNAME/udagram-api-user:v1
  - docker push $DOCKER_USERNAME/udagram-api-feed:v1
  - docker push $DOCKER_USERNAME/reverseproxy:v1
  - docker push $DOCKER_USERNAME/udagram-frontend:v1
  - docker logout